## Adrian Aguilar
# SECTION # 3 - GET STARTED WITH PYTHON FOR DATA SCIENCE 
#1. Libraries or Modules

import math
math.sqrt(25)


In [10]:
import math 
math.pi


3.141592653589793

In [11]:
import math as mt
mt.sqrt(25)

5.0

In [12]:
#2. In your notebook import the following modules and experiment with some of 
#the predefined functions within each module; use the the reference in the resources as a guide:
import numpy 
import math 

#3. Now use numpy to establish some random data we can work with as follows:
from numpy import random
import numpy as np

In [13]:
# uniform random numbers in [0,1]
dataOne = random.rand(5,5)
dataOne

array([[0.50194881, 0.75009965, 0.89896149, 0.45010572, 0.36385189],
       [0.69468982, 0.61713274, 0.16514782, 0.4668065 , 0.93375242],
       [0.55355302, 0.94705639, 0.78045494, 0.27118267, 0.91806622],
       [0.13395129, 0.51168346, 0.08672111, 0.71779969, 0.54502974],
       [0.2349512 , 0.92400402, 0.8423576 , 0.28671794, 0.79105111]])

In [14]:
#4. Now we use a the mean function from within numpy to obtain the mean of the entire array of numbers as follows:
np.mean(dataOne)

0.5754830912794725

In [15]:
#5. Now it is your turn! Use three predefined functions with math and stats to obtain information about the data stored 
#in the numpy array; note any issues you encounter along the way as comments in your notebook. 
#These will serve you well later as lesson learned that you have documented and can reference.

#Zaily's notes: https://docs.python.org/3/library/math.html 

math.factorial(10) #Return x factorial as an integer. Raises ValueError if x is not integral or is negative.

3628800

In [16]:
x=10000
math.isfinite(x) #Return True if x is neither an infinity nor a NaN, and False otherwise.

True

In [17]:
n=10 
math.modf(n) #Return the fractional and integer parts of x. Both results carry the sign of x and are floats.

(0.0, 10.0)

In [18]:
np.array([1, 2, 3])

array([1, 2, 3])

In [19]:

np.array(np.mat('1 2; 3 4'), subok=True)

matrix([[1, 2],
        [3, 4]])

In [20]:

x = np.array([(1,2),(3,4)],dtype=[('a','<i4'),('b','<i4')])
x['a']

array([1, 3], dtype=int32)

In [21]:

##FUNCTIONS 

print('I Love data Science')

I Love data Science


In [22]:

##VARIABLES

z = 25
variableName1 = 'I Love data Science'

print(variableName1)
print(z)

I Love data Science
25


In [23]:

#DATATYPES 
z = 25
type (z)

int

In [24]:
y = 25.0
type (y)

float

In [25]:
varOne = 25
varTwo = 25.0

varThree = varOne + varTwo
print(varThree)

50.0


In [33]:
varOne = 25
varOne = str(varOne)
varTwo = 'Hello '
varThree = varOne + varTwo
print(varThree)

25Hello 


In [30]:
type (varOne)


str

In [31]:
type (varTwo)

str

In [2]:
##Lists and Dictionaries
listOne = [1,2,3,4]
print(listOne[1:3])

[2, 3]


In [3]:
#DICTIONARIES 

tel = {'jack': 4098, 'sape': 4139}
tel['jack']

4098

In [51]:
import pprint

#1. Now it is your turn! Try the following in your own notebook:
#Define a variable that represents a dictionary with 5 INT elements
#Use functions from the math module to perform three different math operations on three of the five elements; you may find it easier to define variables for the elements. Feel free to combine elements as needed. 
#Lastly, print out you results separately.


# Vamos a empezar declarando un diccionario vacío
diccionario_vacio = {}

# un diccionario con valores establecidos como literales
datos_personales = {
    "nombre": "John", 
    "apellido": "Smith",
    "edad": 20, 
    "carreras": [
        "Computación", 
        "Física"
    ],
    "universidad": {
        "nombre": "Universidad Super Patito",
        "fundación": 2001
    }
}

# Ahora vamos a preguntarle al diccionario cuales
# son las llaves que tiene
print("keys de Dic datos personales ")
print(datos_personales.keys())

# Ahora vamos a acceder a los valores del diccionario
print("keys de Dic del Key nombre y apellido ")
print(datos_personales["nombre"])
print(datos_personales["apellido"])

# Ahora vamos a modificar el valor de una llave que 
# se encuentra en el diccionario
datos_personales["nombre"] = "Jane"

# Ahora vamos a acceder a los valores del diccionario
print("keys de Dic del Key nombre  cambio ")
print(datos_personales["nombre"])
print(datos_personales["apellido"])

print("Agregar nueva llave email")

# Ahora vamos a agregar una llave que no existía previamente
datos_personales["email"] = "jane.smith@example.com"

pprint.pprint(datos_personales)

# Vamos a imprimir todos los valores de todas las
# llaves que se cuentran en el diccionario
for key in datos_personales.keys():
    print(datos_personales[key])

# Diccionario dentro de un diccionario
print(datos_personales["universidad"]["nombre"])

# Lista dentro de un diccionario
print(datos_personales["carreras"][0])



keys de Dic datos personales 
dict_keys(['nombre', 'apellido', 'edad', 'carreras', 'universidad'])
keys de Dic del Key nombre y apellido 
John
Smith
keys de Dic del Key nombre  cambio 
Jane
Smith
Agregar nueva llave email
{'apellido': 'Smith',
 'carreras': ['Computación', 'Física'],
 'edad': 20,
 'email': 'jane.smith@example.com',
 'nombre': 'Jane',
 'universidad': {'fundación': 2001, 'nombre': 'Universidad Super Patito'}}
Jane
Smith
20
['Computación', 'Física']
{'nombre': 'Universidad Super Patito', 'fundación': 2001}
jane.smith@example.com
Universidad Super Patito
Computación


In [44]:
mt.sqrt(var_z['val5'])


47.138094997570704

In [39]:
#100+22
mt.fsum([var_z['val4'], var_z['val2']])

122.0

In [40]:
math.isinf(var_z['val2']) #Return True if x is a positive or negative infinity, and False otherwise.


False

In [41]:
from math import exp, expm1

exp (var_z['val3']) #Calculate the product of all the elements in the input iterable.
#The default start value for the product is 1.

72004899337.38588